#%RAML 1.0 Library
usage:
types:
  error-resp:
    type: object
    properties:
      code:
        required: false
        type: string
        example: "400"
      message:
        type: string
        required: false

  
  